name: Auto Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/main.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# 设置权限（文件是可以被读写修改的）
permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/runner/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      # 安装 pnpm
      - name: Install pnpm (安装 pnpm)
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      # 安装 node 环境，并设置版本为 16
      - name: Setup Node.js (设置 node 版本)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # 构建项目
      - name: Build (构建)
        run: pnpm run build

      # 8 上传构建产物（actions/upload-artifact@v3 会上传工作流程中的文件，允许您在作业之间共享数据并在工作流程完成后存储数据）
      - name:  Upload build artifacts (上传构建产物)
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist"
      
      # 9 部署 GitHub Pages
      - name: Deploy to GitHub Pages(部署到 GitHub Pages)
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
